name: dorah
description: Dorah is an application for blood donation and request.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Gilroy
      fonts:
        - asset: lib/assets/fonts/Gilroy-ExtraBold.otf
        - asset: lib/assets/fonts/Gilroy-Light.otf
  assets:
    - lib/assets/images/